#!/usr/bin/env node

_ = require("underscore")
var fs = require("fs")

var g = {
  
}

var builtin = {
  set: function (args, g, builtin) {
    g[args[1]] = args[2] 
  },
  assert: function (args, g, builtin) {
    var val1 = g[args[1]]
    var val2 = args[2]
    if (val1 != val2) {
      console.log("Error: " + val1 + " does not equal " + val2)  
    }
  }

}

var mark16EvalLines = function(code, g, builtin) {
  code = code.split("\n") 
  for (var i=0; i<code.length; i++) {
    var line = code[i]    
    mark16EvalLine(line, g, builtin)
  }
}

var mark16EvalLine = function (line, g, builtin) {
  words = line.split(" ") 
  var funcName = words[0]
  //var rest = words.slice(1).join(" ")
  var builtinFunc = builtin[funcName]
  if (builtinFunc) {
    builtinFunc(words, g, builtin) 
  }
}

var code = fs.readFileSync(process.argv[2]).toString()
mark16EvalLines(code, g, builtin)

